//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.Coupons = new HashSet<Coupon>();
        }
    
        public string BusinessID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Category Category { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
