//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon
{
    using System;
    
    public enum Category : int
    {
        Restaurant = 0,
        CarsAccessories = 1,
        Food = 2,
        Vacations = 3,
        Spa = 4
    }
}
